[tool.poetry]
name = "backend2"
version = "0.1.0"
description = ""
authors = ["Peter Xu <dev@we-sense.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
